# Generated by Django 3.1.7 on 2021-11-04 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='cuantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Product quantity'),
        ),
        migrations.AlterUniqueTogether(
            name='orderdetail',
            unique_together={('order', 'product')},
        ),
    ]
